# name=MPK Mini Test
# Generated by MPK Mini 3 Configurator
# https://github.com/egop358/mpk-mini3-configurator

import transport
import mixer
import channels
import ui
import midi


def OnInit():
    ui.setHintMsg("MPK Mini Test loaded")


def OnNoteOn(event):
    if event.midiChan != 9:
        return
    note = event.note

    if note == 16:  # Pad A1 - Play
        transport.start()
        event.handled = True
    elif note == 17:  # Pad A2 - Stop
        transport.stop()
        event.handled = True
    elif note == 18:  # Pad A3 - Record
        transport.record()
        event.handled = True
    elif note == 19:  # Pad A4 - Loop
        transport.setLoopMode()
        event.handled = True
    elif note == 20:  # Pad A5 - Undo
        transport.globalTransport(midi.FPT_Undo, 1, midi.PME_System)
        event.handled = True
    elif note == 21:  # Pad A6 - Redo
        transport.globalTransport(midi.FPT_Undo, -1, midi.PME_System)
        event.handled = True
    elif note == 22:  # Pad A7 - Toggle Mixer
        ui.showWindow(midi.widMixer)
        event.handled = True
    elif note == 23:  # Pad A8 - Toggle Playlist
        ui.showWindow(midi.widPlaylist)
        event.handled = True
    elif note == 32:  # Pad B1 - Unassigned
        pass
    elif note == 33:  # Pad B2 - Unassigned
        pass
    elif note == 34:  # Pad B3 - Unassigned
        pass
    elif note == 35:  # Pad B4 - Unassigned
        pass
    elif note == 36:  # Pad B5 - Unassigned
        pass
    elif note == 37:  # Pad B6 - Unassigned
        pass
    elif note == 38:  # Pad B7 - Unassigned
        pass
    elif note == 39:  # Pad B8 - Unassigned
        pass


def OnNoteOff(event):
    if event.midiChan == 9:
        event.handled = True


def OnControlChange(event):
    cc  = event.controlNum
    val = event.controlVal

    if cc == 80:
        channels.setChannelPitch(channels.selectedChannel(), (val / 127.0) * 2.0 - 1.0)
        event.handled = True

    elif cc == 81:
        event.handled = True

    elif cc == 16:  # K1 - Master Volume
        mixer.setTrackVolume(0, val / 127.0)
        event.handled = True

    elif cc == 17:  # K2 - Track 1 Volume
        mixer.setTrackVolume(1, val / 127.0)
        event.handled = True

    elif cc == 18:  # K3 - Track 2 Volume
        mixer.setTrackVolume(2, val / 127.0)
        event.handled = True

    elif cc == 19:  # K4 - Track 3 Volume
        mixer.setTrackVolume(3, val / 127.0)## Phase 3  Build the full UI

        We just validated the code generator works perfectly. Now build the complete React UI in src/App.jsx and supporting components.

        ---

        ### Visual Design Goal

        The UI should look and feel like the actual MPK Mini 3 hardware. Use this as your reference for layout:
        - Top half: 8 pads in a 4x2 grid (Bank A top row, bottom row)  dark rubber pad squares with colored LED glow
        - Right side: 8 knobs in a 4x2 grid (K1-K4 top, K5-K8 bottom)  circular rotary style
        - Bottom: 25-key mini keyboard (visual only, not interactive)
        - Overall: dark chassis color (#1a1a1a), red accent trim around edges (like the real unit has red highlights)
        - Font: monospace or techy feel

        For a product image reference, use this URL in an <img> tag as a reference banner at the top:
        https://www.bhphotovideo.com/images/images2500x2500/akai_professional_mpk_mini_mk3_mpk_mini_mk3_25_key_1604022.jpg

        ---

        ### Layout Structure

        ```
        
          HEADER: "MPK Mini 3 Configurator" + device name input  
          
             BANK A (red border)       KNOBS K1-K4 (top row)      
                PAD 5  PAD 6  PAD 7  PAD 8     K1   K2   K3   K4    
                   PAD 1  PAD 2  PAD 3  PAD 4   
                                                KNOBS K5-K8 (bottom row)   
                                                   BANK B (green border)     K5   K6   K7   K8          
                                                      PAD 5  PAD 6  PAD 7  PAD 8                           
                                                         PAD 1  PAD 2  PAD 3  PAD 4                           
                                                         
                                                           KEYBOARD (25 keys, visual only  white/black keys)     
                                                           
                                                             FOOTER: [Export Script] button + install instructions  
                                                             
                                                             ```
                                                             
                                                             ---
                                                             
                                                             ### Pad Component (src/components/Pad.jsx)
                                                             # 
                                                             # Each pad is a dark square button (~80x80px) that:
                                                             # - Shows the pad label (e.g. "PAD 1") in small text at top
                                                             # - Shows the assigned action label in the center (e.g. " Play" or "Unassigned")
                                                             # - Has a colored LED glow border when assigned (color by category):
                                                             #   - Transport actions  red glow (#ff4444)
                                                             #   - Mixer actions  blue glow (#4488ff)  
                                                             #   - Channel actions  green glow (#44ff88)
                                                             #   - Window actions  purple glow (#aa44ff)
                                                             #   - Unassigned  dim grey border
                                                             # - Click opens the AssignmentModal for that pad
                                                             # - Hover: slightly lighter background
                                                             # 
                                                             # ---
                                                             # 
                                                             # ### Knob Component (src/components/Knob.jsx)
                                                             # 
                                                             # Each knob is a circular control (~70px diameter) that:
                                                             # - Shows a skeuomorphic rotary knob using CSS (dark circle, indicator line pointing ~7 o'clock)
                                                             # - Shows the knob label below (e.g. "K1")
                                                             # - Shows the assigned action in small text below that
                                                             # - Click opens AssignmentModal for that knob
                                                             # - CC number shown in small text (e.g. "CC 16")
                                                             # 
                                                             ---
                                                             
                                                             ### AssignmentModal (src/components/AssignmentModal.jsx)
                                                             # 
                                                             # A modal/drawer that slides up or appears centered when a pad or knob is clicked:
                                                             # - Title: "Assign [Pad A1 / Knob K1]"
                                                             # - Search input to filter actions
                                                             # - Action list grouped by category with headers:
                                                             #   -  Transport (Play, Stop, Record, Loop, Undo, Redo, Tap Tempo, Metronome, Rewind, Fast Forward)
                                                             #   -  Mixer Volume (Master, Track 18)
                                                             #   -  Mixer Pan (Master, Track 18)
                                                             #   -  Mixer Mute (Track 08)
                                                             #   -  Mixer Solo (Track 08)
                                                             #   -  Channel Rack (Mute Selected, Solo Selected, Volume, Pan)
                                                             #   -  Windows (Toggle Mixer, Toggle Playlist, Toggle Piano Roll, Toggle Channel Rack)
                                                             #   -  Pass-through (None  let FL Studio handle it)
                                                             # - Each action is a clickable row  clicking it assigns and closes the modal
                                                             # - Currently assigned action is highlighted
                                                             # 
                                                             # ---
                                                             # 
                                                             ### Keyboard Component (src/components/Keyboard.jsx)
                                                             # 
                                                             # Visual-only 25-key mini keyboard:
                                                             # - Standard piano layout: white keys wider, black keys narrower and shorter, offset
                                                             # - 25 keys starting from C (C2C4)
                                                             # - White keys: #e8e8e8, Black keys: #1a1a1a
                                                             # - No click interaction needed  just visual
                                                             # - Should look proportionally accurate to mini keyboard
                                                             # 
                                                             # ---
                                                             # 
                                                             # ### ScriptPreview (src/components/ScriptPreview.jsx)
                                                             # 
                                                             # Collapsible panel below the main UI:
                                                             # - Toggle button "Preview Script  / "
                                                             # - When open: shows the full generated Python in a <pre> block with dark background
                                                             # - Monospace font, syntax-highlighted if possible (just color the comments grey, imports cyan, def keywords purple, strings green  via simple regex replace into spans)
                                                             # - "Copy to clipboard" button top-right of the preview
                                                             # 
                                                             # ---
                                                             # 
                                                             # ### App State (src/App.jsx)
                                                             # 
                                                             # Use useState for the full config object matching this schema:
                                                             # ```js
                                                             # {
                                                             #   deviceName: "MPK Mini 3",
                                                             #   pads: {
                                                             #     bankA: [
                                                             #       { id: "A1", note: 16, cc: 16, action: "transport.play", label: "Play" },
                                                             #       { id: "A2", note: 17, cc: 17, action: "transport.stop", label: "Stop" },
                                                             #       { id: "A3", note: 18, cc: 18, action: "transport.record", label: "Record" },
                                                             #       { id: "A4", note: 19, cc: 19, action: "transport.loop", label: "Loop" },
                                                             #       { id: "A5", note: 20, cc: 20, action: "none", label: "Unassigned" },
                                                             #       { id: "A6", note: 21, cc: 21, action: "none", label:}]}}`
        event.handled = True

    elif cc == 20:  # K5 - Master Pan
        mixer.setTrackPan(0, (val / 127.0) * 2.0 - 1.0)
        event.handled = True

    elif cc == 21:  # K6 - Track 1 Pan
        mixer.setTrackPan(1, (val / 127.0) * 2.0 - 1.0)
        event.handled = True

    elif cc == 22:  # K7 - Unassigned
        pass

    elif cc == 23:  # K8 - Unassigned
        pass
